[platformio]
src_dir = main

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0

; Use our sdkconfig.defaults for PM, NimBLE, etc.
; PlatformIO merges this into the generated sdkconfig.

; For debug builds: uncomment these and set CONFIG_ESP_CONSOLE_NONE=n
; and CONFIG_LOG_DEFAULT_LEVEL=3 in sdkconfig.defaults
; build_flags = -DDEBUG
